version: 2.1
jobs:
  test:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - run:
          name: install
          command: |
            pip install pytest
            pip install shapely
            pip install fiona
workflows:
  test:
    jobs:
      - test