version: 2.1
jobs:
  test:
    docker:
      - image: cimg/python:3.9
      - steps:
        - checkout
        - run: |
          pip install pytest
          pytest -s
workflows:
  test:
    jobs:
      - test